### ISSUE TITLE
Why Neo Languages online is blank?

### ISSUE THREAD

**Issue by Femtometer** [hhd-software/hex-editor-localization-pack#4]
![截屏_2022-05-06_12-05-22](https://user-images.githubusercontent.com/5461891/167069369-e921a8d7-fbc9-439b-acf9-301e9b787ef1.png)

**Comment by AlexBAV** [comment]
We cannot reproduce this. If the language is already downloaded (that is, it is shown when you expand the "Product language" combo), it won't be listed in "Languages online" field.

Otherwise, check the Internet connection to hhdsoftware.com.

Language packs are also usually available for the most recent version of the product. Check that you have the most recent version installed.

**Comment by Femtometer** [comment]
> We cannot reproduce this. If the language is already downloaded (that is, it is shown when you expand the "Product language" combo), it won't be listed in "Languages online" field.
> 
> Otherwise, check the Internet connection to hhdsoftware.com.
> 
> Language packs are also usually available for the most recent version of the product. Check that you have the most recent version installed.

Thanks for your reply.
Installed version: 6.54.03, and I can connect to hddsoftware.com in Microsoft edge.
Would you upload "Simplified Chinese" languages pack file, and I manual copy to the Localization folder？

**Comment by AlexBAV** [comment]
[zh.中文(简体).104000001.lpack.zip](https://github.com/hhd-software/hex-editor-localization-pack/files/8644793/zh.104000001.lpack.zip)

**Comment by Mapaler** [comment]
This problem still exists in the latest version.
![HexFrame_0087](https://github.com/hhd-software/hex-editor-localization-pack/assets/6565860/ed70826d-f9d3-477f-931c-db324e6fdd7c)
Try setting up the proxy manually, but turning it on again, the proxy address disappears.
![HexFrame_0088](https://github.com/hhd-software/hex-editor-localization-pack/assets/6565860/12213047-97a8-4fd5-b9a1-657dbb57db91)
Manually placing files also did not search for languages.
![HexFrame_0090](https://github.com/hhd-software/hex-editor-localization-pack/assets/6565860/61413bf5-8082-49cf-8f9e-ff5c7d825bbb)

**Comment by AlexBAV** [comment]
Hex Editor Neo uses BITS service (Microsoft Background Intelligent Transfer Service) to make HTTP requests to check for updates and for new language packs.

Standard OS configuration has its service enabled, but it may be manually disabled by the user. Please check if this is your case.
