### ISSUE TITLE
Hex Editor Neo - Korean Pack

### ISSUE THREAD

**Issue by VenusGirl** [hhd-software/hex-editor-localization-pack#5]
Hex Editor Neo 7.09.01.8132 - Korean Pack

[ko.한국어.105020001.lpack.zip](https://github.com/hhd-software/hex-editor-localization-pack/files/9695862/ko.105020001.lpack.zip)

**Comment by AlexBAV** [comment]
Thank you @VenusGirl for your contribution of a Korean Language Pack!

Would it be possible for you to submit a Pull Request with sources to this repository?

In addition, you may know that we give free Ultimate licenses for the Hex Editor Neo product to those who contribute language packs. Please let us know if you are interested and also optionally provide us with credits information, if you want it to be visible in the editor.

**Comment by VenusGirl** [comment]
[Hex-editor-Korean-pack.zip](https://github.com/hhd-software/hex-editor-localization-pack/files/9696104/Hex-editor-Korean-pack.zip)

Korean translator: VenusGirl (비너스걸)
Email: venusgirl@outlook.com

**Comment by AlexBAV** [comment]
> [Hex-editor-Korean-pack.zip](https://github.com/hhd-software/hex-editor-localization-pack/files/9696104/Hex-editor-Korean-pack.zip)
> 
> Korean translator: VenusGirl (비너스걸) Email: [venusgirl@outlook.com](mailto:venusgirl@outlook.com)

Thank you. I've sent you an e-mail with instructions on how to proceed.

Meanwhile, we will validate the LP and publish it as soon as possible.
